### ISSUE TITLE
Mod fails to generate a config file

### ISSUE THREAD

**Issue by VaelophisNyx** [adambennett/MT-StartingGoldMod#1]
As the title says, the mod will fail to make a config file and as such you cannot set your money, which defaults to 50

"[Error  :   BepInEx] Could not load [Moneybags 1.1.1.0] because it has missing dependencies: api.modding.train.monster"
T'would appear that the API got renamed but this dependency listing didn't follow suit

**Comment by adambennett** [comment]
This problem is still under investigation, to those that may be curious. Sorry for the long delay.
